apiVersion: v1
kind: Pod
metadata:
  name: nginx-b
#  namespace: sandbox
spec:
  containers:
  - name: nginx
    image: nginx:1.14.1
    env:
    - name: SECRET_USERNAME
      valueFrom:
        secretKeyRef:
          name: ckyal-secret
          key: password
    ports:
    - containerPort: 80